name = "namorim"
type = "javascript"
main = "src/main.js"

[env.production]
routes = [
  { pattern = "namorim.pages.dev", zone_name = "namorim.pages.dev" }
]

[build]
command = "bun run build"
cwd = "./"
outdir = "dist"

[build.upload]
format = "service-worker"
main = "./"

[env.production.build]
command = "bun run build"
